Lapkart/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('user_home.urls')),
    path('login/',include('useraccount.urls')),
    path('userprofile/', include('user_profile.urls')),
    path('store/', include('store.urls')),
    path('add-to-cart/',include('cart.urls')),
    path('checkout/', include('checkout.urls')),
    path('myorders/', include('order.urls')),
    path('wishlist/', include('wishlist.urls')),
    path('dashboard/', include('dashboard_home.urls')),
    path('brandlist/', include('dashboard.urls')),
    path('adminprofile/', include('dashboard_users.urls')),
    path('productlist/',include('admin_product.urls')),
    path('bannerlist/', include('admin_banner.urls')),
    path('orderlist/', include('admin_order.urls')),
    path('offerlist/', include('admin_offer.urls')),
    path('apply_coupon/', include('coupon.urls')),
    path('variantlist/', include('admin_variant.urls'))
    
    
    
    
    
    
    
    
    
    
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

cart/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.add_to_cart, name = 'add-to-cart'),
    path('cart/', views.cart, name='cart'),
    path('delete-from-cart/',views.deleteCartItem, name='delete-from-cart'),
    path('update-cart/', views.updateCartItem, name="update-cart")
    
 
   
]

checkout/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.checkout, name = 'checkout'),
    path('place-order/', views.placeorder, name = 'placeorder'),
    path('proceed-to-pay/', views.razorpaycheck, name = 'razorpaycheck'),
 
   
]

order/urls.py
from django.urls import path,re_path
from .  import views





urlpatterns = [
    path('', views.myOrders, name = 'myOrders'),
    path('orderView/<str:t_no>/', views.orderview, name='orderview'),
    path('myorders/user_order_track/<int:id>/', views.user_order_track, name='user_order_track'),

    path('ordercancel/', views.ordercancel, name='ordercancel')
]
    
  
    

    
   
    
    
    
    
    

checkout/models.py
from django.db import models
from useraccount.models import Account
import string
import random
from datetime import datetime
from store.models import Product,ProductAttribute
from user_profile.models import User_Address

# Create your models here.
class Coupon(models.Model):
    coupon_code = models.CharField(max_length=10)
    is_expired = models.BooleanField(default=False)
    discount_price = models.PositiveIntegerField(default=100)
    minimum_amount = models.PositiveIntegerField(default=500)
    is_applied = models.BooleanField(default=False)
    
    def __str__(self):
        return self.coupon_code
     # Create your models here.
def generate_order_id():
    """Generate a 14-character order ID"""
    while True:
        letters = string.ascii_uppercase + string.digits
        order_id = ''.join(random.choice(letters) for i in range(9))
        year = str(datetime.now().year)[-2:]
        month = str(datetime.now().month)[-2:]
        day = str(datetime.now().day)
        hour = str(datetime.now().hour)
        new_id = 'LK' + month + day + hour+ order_id
        return new_id
    
class Payment_methods(models.Model):
    method = models.CharField(max_length=100)

    def __str__(self) -> str:
        return self.method
        

class Order(models.Model):
    order_id = models.CharField(max_length=20, default=generate_order_id, unique=True)
    user = models.ForeignKey(Account, on_delete=models.CASCADE)
    user_address = models.ForeignKey(User_Address, on_delete=models.CASCADE)
    total_price = models.FloatField(null=False)
    payment_mode = models.ForeignKey(Payment_methods, on_delete=models.CASCADE)
    payment_id = models.CharField(max_length=250, null=True)
    paid = models.BooleanField(default=False, null=True)
    message = models.TextField(null=True)
    tracking_no = models.CharField(max_length=150, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    

    


    
    def __str__(self) -> str:
        return self.order_id




class Order_item(models.Model):
   
    user = models.ForeignKey(Account, on_delete=models.CASCADE)
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    variant = models.ForeignKey(ProductAttribute,on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField()
    image = models.ImageField(upload_to='photos/order')
    price = models.PositiveIntegerField()
    total=models.PositiveIntegerField()
    ORDER_STATUS_CHOICES = [
        ('Pending', 'Pending'),
        ('Processing', 'Processing'),
        ('Out for Shipping', 'Out for Shipping'),
        ('Shipped', 'Shipped'),
        ('Delivered', 'Delivered'),
        ('Cancelled', 'Cancelled'),
        ('Refunded', 'Refunded'),
    ]
    status = models.CharField(max_length=20, choices=ORDER_STATUS_CHOICES, default='pending')
    
    

    def get_total(self):
        return self.variant.price * self.quantity
    
    def __str__(self) -> str:
        return str(self.order)






    

store/models.py
from django.db import models
from user_brand.models import Brand
from user_category.models import Category
from django.utils.text import slugify
from django.utils.html import mark_safe

# Create your models here.
class screenSizeVariant(models.Model):
    size_name = models.CharField(max_length=100)
    price = models.IntegerField(default=0)
    stock = models.PositiveIntegerField(default=0)
    
    def __str__(self):
        return self.size_name
    
class RAMVariant(models.Model):
    RAM_name = models.CharField(max_length=100)
    price = models.IntegerField(default=0)
    stock = models.PositiveIntegerField(default=0)
    
    def __str__(self):
        return self.RAM_name
    
# class price_filter(models.Model):
#     filter_price = (
        
#         ('1000 T 10000', '1000 TO 10000'),
#         ('10000 TO 20000', '10000 TO 20000'),
#         ('20000 TO 30000', '20000 TO 30000'),
#         ('30000 TO 40000', '30000 TO 40000'),
#         ('40000 TO 50000', '40000 TO 50000'),
#         ('50000 and above', '50000 and above'),
        
#         )
#     price = models.CharField(choices=filter_price, max_length=60)
    
#     def __str__(self):
#         return self.price
    
    
class Offer(models.Model):
    offer_name = models.CharField(max_length=100)
    discount_amount = models.PositiveIntegerField()
    
    def __str__(self):
        return self.offer_name





class Product(models.Model):
    slug = models.SlugField(max_length=100, unique = True)
    product_name = models.CharField(unique=True,max_length=50)
    brand = models.ForeignKey(Brand,on_delete=models.CASCADE)
    category = models.ForeignKey(Category,on_delete=models.CASCADE)
    product_description = models.TextField(blank=True)
    price = models.PositiveIntegerField(default=0)
    size = models.ForeignKey(screenSizeVariant, on_delete=models.CASCADE, blank=True, null=True)
    ram = models.ForeignKey(RAMVariant,on_delete=models.CASCADE, blank=True, null=True)
    status = models.BooleanField(default=True)
    
    
    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.product_name)
        super(Product, self).save(*args, **kwargs)
    
    

    def __str__(self):
        return self.product_name
    
   

class Product_Image(models.Model):
    product = models.ForeignKey(Product ,on_delete=models.CASCADE)
    image = models.ImageField(upload_to='photos/product')
   
    def __str__(self) -> str:
        return str(self.product)


class ProductAttribute(models.Model):
      product = models.ForeignKey(Product, on_delete=models.CASCADE)
      size = models.ForeignKey(screenSizeVariant, on_delete=models.CASCADE)
      ram = models.ForeignKey(RAMVariant, on_delete=models.CASCADE)
      price = models.PositiveIntegerField()
      image = models.ImageField(upload_to='photos/product',null=True)
      stock = models.PositiveIntegerField()
      offer = models.ForeignKey(Offer, on_delete=models.CASCADE, blank=True, null=True)
      
      def get_offer(self):
        return self.price - self.offer.discount_amount
      
      def image_tag(self):
          return mark_safe('<img src="%s" width="50" height="50" />' % (self.image.url))
      
      def __str__(self):
            return self.product.product_name
        
        

checkout/views.py
from django.shortcuts import render, redirect
from cart.models import Cart, CartItem
from coupon.models import Coupon,Usercoupon
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from useraccount.models import Account
from user_profile.models import User_Address
from . models import Order, Order_item, Payment_methods
from store.models import Product
import random
from django.http import JsonResponse,HttpResponseRedirect

from django.views.decorators.cache import cache_control
from order.models import Wallet




# Create your views here.

@cache_control(no_cache=True, must_revalidate=True,no_store=True)
def checkout(request):
    rawcart = CartItem.objects.filter(cart__user=request.user)
    cart_obj = Cart.objects.filter(is_paid=False, user=request.user).first()
    carts = Cart.objects.filter(user=request.user)
    
    # Remove cart items where product_quantity exceeds size_variant stock
    coupon_code = request.POST.get('coupon_code')

    address = User_Address.objects.filter(user=request.user)
    cartitems = CartItem.objects.filter(cart__user=request.user)
    tax = 0
    subtotal = 0
    grandtotal = 0
    
    
    
    
    for item in cartitems:
        if item.variant.offer:
            subtotal += item.product_quantity*item.variant.get_offer()
        else:
            subtotal += item.product_quantity*item.variant.price
        
    tax = round(subtotal * 0.18)
    
    grandtotal = subtotal + 70 + tax
   
    
    usercoupon = Usercoupon.objects.filter(user=request.user).last()
    coupons = Coupon.objects.all()
        
        
    userprofile = User_Address.objects.filter(user=request.user).first()
   
 
    
    
    context = {
        'cartitems': cartitems,
        'subtotal': subtotal,
        'grandtotal': grandtotal,
        'tax' : tax,
        'usercoupon' : usercoupon,
        'userprofile' : userprofile,
        'cart' : cart_obj,
        'carts' : carts,
        'coupons' : coupons,
        'address' : address
        
    }
    
    return render(request, 'checkout/checkout.html', context)

@cache_control(no_cache=True, must_revalidate=True, no_store=True)
def placeorder(request):
    if request.method == "POST":
        currentuser = Account.objects.filter(id=request.user.id).first()
        payment_mode_value = request.POST.get('payment_mode')
        payment_mod = Payment_methods.objects.get(method__icontains=payment_mode_value)
        # userprofile = User_Address.objects.filter(user=request.user).first()
        address_id=request.POST.get('address')
        

        if address_id is None:
            messages.error(request,"Address field are mandatory")
            return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

        neworder = Order()
        address = User_Address.objects.get(id=address_id)
        neworder.user_address = address
        neworder.user = request.user
        neworder.payment_mode = payment_mod
        neworder.payment_id = request.POST.get('payment_id')
        
  
        
        

        cartitems = CartItem.objects.filter(cart__user=request.user)
        cart_obj = Cart.objects.filter(is_paid=False, user=request.user).first()
        tax = 0
        subtotal = 0
        grandtotal = 0

        for item in cartitems:
            subtotal += item.product_quantity*item.variant.price

        tax = subtotal * 0.18

        grandtotal = subtotal + tax + 50
        
        if (payment_mod.method == "Wallet"):
            try:
                wallet = Wallet.objects.get(user=request.user)
            except Wallet.DoesNotExist:
                wallet = Wallet.objects.create(user=request.user, wallet=0)
            
            if wallet.wallet >= grandtotal:
                wallet.wallet = wallet.wallet-grandtotal
                wallet.save()
            else:
                messages.error(request,'Your wallet amount is very low')
                return redirect('checkout')
            
        if Usercoupon.objects.filter(user = request.user).exists():
            usercoupon = Usercoupon.objects.get(user = request.user)
            neworder.total_price = usercoupon.total_price
            usercoupon.delete()
        else:
            neworder.total_price = grandtotal
        
        

        if cart_obj:
            trackno = 'LapK' + str(random.randint(1111111, 9999999))
            while Order.objects.filter(tracking_no=trackno) is None:
                trackno = 'LapK' + str(random.randint(1111111, 9999999))

            neworder.tracking_no = trackno
            neworder.save()

            neworderitems = CartItem.objects.filter(cart__user=request.user)

            for item in neworderitems:
                Order_item.objects.create(
                    user=request.user,
                    order=neworder,
                    product=item.product,
                    price=item.variant.price,
                    quantity=item.product_quantity,
                    total=grandtotal,
                    image=item.variant.image,
                    variant=item.variant
                )

                item.variant.stock -= item.product_quantity
                item.save()

            # To clear cart
            Cart.objects.filter(user=request.user).delete()
            
          

            payMode = request.POST.get('payment_mode')
            if payMode == "Razorpay":
                return JsonResponse({'status': "Your order has been placed"})
            else:
                messages.success(request, "Your order has been placed successfully")

    return render(request, 'checkout/checkout.html')



def razorpaycheck(request):
    cart = CartItem.objects.filter(cart__user=request.user)
    cart_obj = Cart.objects.get(is_paid = False, user=request.user)
    tax = 0
    subtotal = 0
    grandtotal = 0
    
    for item in cart:
        subtotal += item.product_quantity*item.variant.price
        
    tax = subtotal * 0.18
    grandtotal=subtotal + tax + 70


            
    return JsonResponse({
        'total_price' : grandtotal
    })
    
    

order/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseRedirect
from checkout.models import Order,Order_item
from django.shortcuts import render, get_object_or_404
from store.models import Product
from order.models import Wallet


# Create your views here.
def myOrders(request):
    orders = Order.objects.filter(user=request.user).order_by('-id')
    context = {}
    if orders:
        context = {
            'orders': orders
        }
    return render(request, 'checkout/placeOrder.html', context)



def orderview(request, t_no):
      order = Order.objects.filter(tracking_no=t_no).filter(user=request.user).first()
      orderitems = Order_item.objects.filter(order=order)
      context = {
            'order' : order,
            'orderitems' : orderitems,
      }
      
      return render(request, 'checkout/orderview.html', context)





def user_order_track(request, id):
    order_item = get_object_or_404(Order_item, id=id)
    
    orderstatus = [
        (Order_item.ORDER_STATUS_CHOICES.index(choice) + 1, choice[1]) for choice in Order_item.ORDER_STATUS_CHOICES
    ]
      
    statusIndex = {
        'pending': 1,
        'processing': 2,
        'out for shipping': 3,
        'shipped': 4,
        'delivered': 5,
        'cancelled': 6,
        'refunded': 7,
    }

    trackIndex = 0
    for value, idx in statusIndex.items():
        if value.lower() == order_item.status.lower():
            trackIndex = idx 
            break
    
    context = {
        'order_item': order_item,
        'orderstatus': orderstatus,
        'trackIndex': trackIndex
    }
    
    return render(request, "checkout/trackorder.html", context)





# Order Cancel
from django.http import HttpResponseBadRequest
def ordercancel(request):
    orderid = request.POST.get('order_id')
    orderitem_id = request.POST.get('orderitem_id')
    # Check if orderitem_id is valid
    if not orderitem_id:
        return HttpResponseBadRequest("Invalid orderitem_id")

    try:
        orderitem_id = int(orderitem_id)
    except ValueError:
        return HttpResponseBadRequest("Invalid orderitem_id")

    orderitem = Order_item.objects.filter(id=orderitem_id).first()

    if not orderitem:
        return HttpResponseBadRequest("Order item not found")

    order = Order.objects.filter(id=orderid).first()
    qty = orderitem.quantity
    pid = orderitem.product.id
    product = Product.objects.filter(id=pid)
    
    
    if order.payment_mode.method == 'Razorpay':
        order = Order.objects.get(id=orderid)
        total_price = order.total_price
        try:
            wallet = Wallet.objects.get(user=request.user)
            wallet.wallet += total_price
            wallet.save()
        except Wallet.DoesNotExist:
            wallet = Wallet.objects.create(user=request.user, wallet=total_price)
       
       


    orderitem.quantity = 0
    orderitem.status = 'Cancelled'
    orderitem.save()
    order.save()
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

templates/checkout/orderview.html
{% extends 'user_home/base.html'%}
{% load static %}
{% block title %}
Order View
{% endblock %}
{% block headlink %}
  <link rel="stylesheet" href="{% static 'assetUser/css/price_rangs.css' %}">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw==" crossorigin="anonymous" referrerpolicy="no-referrer" />
  <!-- style CSS -->
{% endblock %}

{% block content %}
{% include 'includes/navbar.html' %}


  <!--================Home Banner Area =================-->
  <!-- breadcrumb start-->
  <section class="breadcrumb breadcrumb_bg">
    <div class="container">
      <div class="row justify-content-center">
        <div class="col-lg-8">
          <div class="breadcrumb_iner">
            <div class="breadcrumb_iner_item">
              <h2>Order Confirmation</h2>
              <p><a href= "{% url 'home' %}"> Home </a><span>></span><a href= "{% url 'myOrders' %}"> My Orders </a><span>></span>Order View</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
  <!-- breadcrumb start-->

  <!--================ confirmation part start =================-->
  <section class="confirmation_part padding_top">
    <div class="container">
      <div class="row">
        <div class="col-lg-12">
          <div class="confirmation_tittle">
            <span>Thank you. Your order has been received.</span>
          </div>
        </div>
        
        <div class="col-lg-6 col-lx-4">
          <div class="single_confirmation_details">
            <h4>Shipping Address</h4>
            <ul>
              <li>
                <p>Name</p><span>: {{order.user_address.firstname}}</span>
              </li>
              <li>
                  <p>Phone No</p><span>: {{order.user_address.contact_number}}</span>
                </li>
              <li>
                  <p>Address</p><span>: {{order.user_address.address}}</span>
                </li>
                <li>
                  <p>City</p><span>: {{order.user_address.city}}</span>
                </li>
                <li>
                  <p>District</p><span>: {{order.user_address.district}}</span>
                </li>
              <li>
                <p>State</p><span>: {{order.user_address.state}}</span>
              </li>
              <li>
                <p>Country</p><span>: {{order.user_address.country}}</span>
              </li>
              <li>
                <p>Postcode</p><span>: {{order.user_address.pincode}}</span>
              </li>
            </ul>
          </div>
        </div>
        <div class="col-lg-6 col-lx-4">
            <div class="single_confirmation_details">
              <h4>order info</h4>
              <ul>
                <li>
                  <p>Tracking No</p><span>: {{order.tracking_no}}</span>
                </li>
                <li>
                  <p>Order Date</p><span>: {{order.created_at}}</span>
                </li>
                <li>
                  <p>Total Amount</p><span>: {{order.total_price}}</span>
                </li>
                <li>
                  <p>Payment Method</p><span>: {{order.payment_mode}}</span>
                </li>
              </ul>
            </div>
          </div>
      </div>
      <div class="row">
        <div class="col-lg-12">
          <div class="order_details_iner">
            <h3>Order Details</h3>
            <table class="table table-borderless">
              <thead>
                <tr>
                  <th scope="col" colspan="2">Name</th>
                  <th scope="col">Quantity</th>
                  <th scope="col">Price</th>
                  <th scope="col">Image</th>
                  
                </tr>
              </thead>
              <tbody>
                {% for item in orderitems%}
                <tr>
                  <th colspan="2"><span>{{item.product.product_name}}</span></th>
                  <th>{{item.quantity}}</th>
                  <th> <span>{{item.price}}</span></th>
                  <th>{% if item.product.product_image_set.exists %}
                <img style="width:70px;heigth:70px" src="{{ item.product.product_image_set.first.image.url }}" alt="Product Image">
            {% else %}
                No Image Available
            {% endif %}
                  </th>
                  <th>
                    {% if item.status != 'Cancelled' %}
                    <!-- Button trigger modal -->
                    <button type="button" class="btn btn-outline-danger" data-bs-toggle="modal" data-bs-target="#exampleModals{{ forloop.counter }}">
                        Cancel
                    </button>
                    {% else %}
                    Cancelled
                    {% endif %}
                    <!-- Modal for deleting the product -->
                    <div class="modal fade cartdata" id="exampleModals{{ forloop.counter }}" tabindex="-1" aria-labelledby="exampleModalLabel{{ forloop.counter }}" aria-hidden="true">
                        <div class="modal-dialog">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h1 class="modal-title fs-5" id="exampleModalLabel{{ forloop.counter }}">Confirm Cancel</h1>
                                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                </div>
                                <div class="modal-body">
                                    Cancel Product {{ odritem.product.product_name }}
                                </div>
                                <div class="modal-footer">
                                  {% csrf_token %}
                                  <input type="hidden" class="order_id" value="{{ item.order.id }}">
                                  <input type="hidden" class="orderitem_id" value="{{ item.id }}">
                                    <button type="submit" class="btn btn-danger ordercancel">Confirm</button>
                                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                                </div>
                            </div>
                        </div>
                    </div>
                    <!-- Deleting ended -->
                </th>
                {% if item.status != 'Cancelled' %}
                <th>
               

                    <a href="{% url 'user_order_track' item.id %}" class="btn btn-outline-secondary" title="Track Status">Track order</a>
                  
                </th>
                {% endif %}
            
               
                {% endfor %}
                
                
              <tfoot>
                
              </tfoot>
            </table>
          </div>
        </div>
      </div>
    </div>
  </section>
  <!--================ confirmation part end =================-->


{% endblock %}

{% block bottomlink %}
<script src="https://code.jquery.com/jquery-3.7.0.min.js" integrity="sha256-2Pmvv0kuTBOenSvLm6bvfBSSHrUJ+3A7x6P5Ebd07/g=" crossorigin="anonymous"></script>


<script>
  $(document).ready(function() {
      $('.ordercancel').click(function(e) {
        e.preventDefault();
    
        var order_ids = $(this).closest('.modal-content').find('.order_id').val();
        var orderitem_ids = $(this).closest('.modal-content').find('.orderitem_id').val();
        var token = $("[name='csrfmiddlewaretoken']").val();
        console.log(order_ids,'daxo')
        var modal = $(this).closest('.modal');
        
        $.ajax({
          method: "POST",
          url: "{% url 'ordercancel' %}",
          data: {
            'order_id': order_ids,
            'orderitem_id': orderitem_ids,
            csrfmiddlewaretoken: token
          },
          success: function(response) {
            console.log(response);
            alertify.success(response.status);
    
            location.reload();
          },
          error: function(xhr, status, error) {
            console.log(xhr.responseText);
            // Handle error case
          }
        });
      });
    });
    
</script>

  <script src="{% static 'assetUser/js/stellar.js' %}"></script>
  <script src="{% static 'assetUser/js/price_rangs.js' %}"></script>

{% endblock %}

templates/checkout/placeOrder.html
{% extends 'user_home/base.html'%}
{% load static %}
{% block title %}
Confirm order
{% endblock %}
{% block headlink %}
  <link rel="stylesheet" href="{% static 'assetUser/css/price_rangs.css' %}">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw==" crossorigin="anonymous" referrerpolicy="no-referrer" />
  <!-- style CSS -->
{% endblock %}

{% block content %}

{% include 'includes/navbar.html' %}

  <!--================Home Banner Area =================-->
  <!-- breadcrumb start-->
  <section class="breadcrumb breadcrumb_bg">
    <div class="container">
      <div class="row justify-content-center">
        <div class="col-lg-8">
          <div class="breadcrumb_iner">
            <div class="breadcrumb_iner_item">
              <h2>Order Confirmation</h2>
              <p>Home <span>></span> Order Confirmation</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
  <!-- breadcrumb start-->
 


  <!--================ confirmation part start =================-->
  <section class="confirmation_part padding_top">
    <div class="container">
      <div class="row">
        <div class="col-lg-12">
          <div class="confirmation_tittle">
            <span>Thank you. Your order has been received.</span>
          </div>
        </div>

      <div class="row">
        <div class="col-lg-12">
          <div class="order_details_iner">
            <h3>Order Details</h3>
            <table class="table table-borderless">
              <thead>
                <tr>
                  <th scope="col" colspan="2">Order Date</th>
                  <th scope="col">Tracking No</th>
                  <th scope="col">Total Price</th>
                  
                  <th scope="col">Action</th>
                </tr>
              </thead>
              <tbody>
                {% if orders %}
                {% for order in orders %}
                    <!-- Iterate over order details -->
                    <tr>
                        <th colspan="2"><span>{{ order.created_at }}</span></th>
                        <th>{{ order.tracking_no }}</th>
                        <th><span>{{ order.total_price }}</span></th>
                        
                        <th>
                            <span>
                                <a href="{% url 'orderview' order.tracking_no %}" class="btn btn-primary">
                                    View <i class="fas fa-eye"></i>
                                </a>
                            </span>
                        </th>
                    </tr>
                {% endfor %}
            {% else %}
                <tr>
                    <td colspan="6">No orders found</td>
                </tr>
            {% endif %}
            
            </tbody>
            
              <tfoot>
              
              </tfoot>
            </table>
          </div>
        </div>
      </div>
    </div>
  </section>
  <!--================ confirmation part end =================-->
  

{% endblock %}

{% block bottomlink %}

  <script src="{% static 'assetUser/js/stellar.js' %}"></script>
  <script src="{% static 'assetUser/js/price_rangs.js' %}"></script>

{% endblock %} 